# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
# that happened during the last build.
trigger:
  batch: true
  branches:
    include:
    - feature/*
    - standalone-template
  paths:
    include:
    - '*'
    exclude:
    - eng/Version.Details.xml
    - .github/*
    - docs/*
    - src/docs/*
    - CODE-OF-CONDUCT.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

variables:
- template: /eng/pipelines/common/variables.yml@self
  parameters:
    templatePath: 'templates-official'

- ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
  - name: TeamName
    value: dotnet-core
extends:
  template: /eng/pipelines/common/templates/template1es.yml@self
  parameters:
    stages:
    - stage: Build
      jobs:
      - template: /eng/pipelines/common/templates/build-job.yml
        parameters:
          osGroup: OSX
          archType: x64
          isOfficialBuild: true
          runTests: false
          pool:
            name: Azure Pipelines
            image: macos-latest
            os: macOS
          bindings:
            isBindingsBuild: true
            scriptArgs: '--platform MacOSX --arch arm64e-apple-macos --framework StoreKit --experimental'

    - ${{ if eq(variables.isOfficialBuild, true) }}:
      - template: /eng/pipelines/common/templates/publish.yml
        parameters:
          isOfficialBuild: true
          enableSourceLinkValidation: true
